services:
  db19: # Cambiamos 'db' por 'db19' para que coincida con el HOST
    image: postgres:15-alpine
    container_name: odoo19-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./odoo19-db-data:/var/lib/postgresql/data
    networks:
      - network_odoo_19
    ports:
      - "5433:5432"
    restart: always

  odoo:
    image: odoo:19.0
    container_name: odoo19_jc_1
    depends_on:
      - db19 # Debe apuntar al nombre exacto del servicio de arriba
    ports:
      - "8070:8069"
    environment:
      - HOST=db19 # Ahora sí coincidirá
      - USER=odoo
      - PASSWORD=odoo
      - PROXY_MODE=False
    volumes:
      - ./enterprise-19.0:/mnt/enterprise-addons # Es común ver una carpeta para enterprise
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo19_data:/var/lib/odoo
    networks:
      - network_odoo_19
    restart: always

volumes:
  odoo19-db-data:
  odoo19_data:

networks:
  network_odoo_19:
