{
    "name": "Access Studio - Easy, Unified & User-Friendly Odoo Simplified Access Management",
    "version": "18.0.2.0.1",
    "category": "Tools",
    "summary": "Manage Odoo access with ease - one app for menus, fields, views & more. No complexity, just control.",
    "description": """
Hide Menus,
Hide Reports,
Hide Drop-down Actions on List, Form views,
Hide Views,
Hide Create,
Hide Edit,
Hide Delete,
Hide Archive,
Hide Unarchive,
Hide Import,
Hide Export,
    """,
    "author": "IniyaSoft Technologies",
    "website": "https://iniyasoft.com",
    "license": "OPL-1",
    "depends": ["base", "web", "mail", "base_import"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_ui_view_type_data.xml",
        "views/access_studio_views.xml",
        "views/user_group_views.xml",
        "views/res_users_views.xml",
        "views/menuitem.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "access_studio/static/src/js/*",
            "access_studio/static/src/components/**/*",
            "access_studio/static/src/views/**/*",
        ],
    },
    "images": ["static/description/banner.gif"],
    "post_init_hook": "post_install_action_hook",
    "price": 299.99,
    "currency": "EUR",
    "installable": True,
    "application": True,
    "live_test_url": "https://demo-odoo18-access_studio.iniyasoft.com/",
    "support": "iniyasoft.legal@gmail.com",
    "sequence": 0,
}
